version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb-city
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data: